import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import Link from "next/link";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = (await getServerSession(authOptions as any)) as any;
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gray-50`}>
        <header className="h-12 bg-white border-b border-[var(--card-border)] flex items-center justify-between px-4">
          <Link href="/" className="font-semibold">Daily Planner</Link>
          <nav className="text-sm text-gray-600">
            {session?.user ? (
              <span>こんにちは、{session.user.name ?? session.user.email}</span>
            ) : (
              <Link href="/auth/signin" className="text-blue-600">ログイン</Link>
            )}
          </nav>
        </header>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
